[build]
builder = "NIXPACKS"
buildCommand = """
cd backend
python -m ensurepip --upgrade
pip install --upgrade pip
pip install -r requirements.txt
"""

[deploy]
startCommand = "cd backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["python311"]